import "./globals.css";
import type { Metadata } from "next";
import { Toaster } from "react-hot-toast";
import { KoHo, Montserrat } from "next/font/google";
import localFont from "next/font/local"; 

import AosProvider from "@/Provider/AosProvider/AosProvider";
import AuthProvider from "@/Provider/AuthProvider/AuthProvider";
import QueryProvider from "@/Provider/QueryProvider/QueryProvider";

const koho = KoHo({
  subsets: ["latin"],
  weight: ["200", "300", "400", "500", "600", "700"],
  variable: "--font-koho",
  display: "swap",
});
const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
  display: "swap",
});

const integralCF = localFont({
  src: [
    {
      path: "../../public/font/Fontspring-DEMO-integralcf-regular.otf",
      weight: "400",
      style: "normal",
    },
    {
      path: "../../public/font/Fontspring-DEMO-integralcf-medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/font/Fontspring-DEMO-integralcf-demibold.otf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/font/Fontspring-DEMO-integralcf-bold.otf",
      weight: "700",
      style: "normal",
    },
    {
      path: "../../public/font/Fontspring-DEMO-integralcf-extrabold.otf",
      weight: "800",
      style: "normal",
    },
    {
      path: "../../public/font/Fontspring-DEMO-integralcf-heavy.otf",
      weight: "900",
      style: "normal",
    },
  ],
  variable: "--font-integral-cf",
  display: "swap",
});

export const metadata: Metadata = {
  title: "zollani",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html
      lang="en"
      className={` ${montserrat.variable} ${koho.variable} ${integralCF.variable}`} 
    >
      <body className="font-koho antialiased">
        <QueryProvider>
          <AuthProvider>
            <AosProvider>
              <Toaster />
              {children}
            </AosProvider>
          </AuthProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
